###
Post http://localhost:3000/auth
Content-Type: application/json

{
    "email": "biel@email.com",
    "password": "Gabriel1"
}

###
Get http://localhost:3000/movies
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMjIyNzBjNi1jNTg5LTQ3NWEtYTE1NS1jMTc3YTU3MzNiYjQiLCJlbWFpbCI6ImJpZWxAZW1haWwuY29tIiwiaWF0IjoxNzE1NDYwMjM1LCJleHAiOjE3MTU1NDY2MzV9.GhCVHctCuQ-db50rD-23-UsJjEpKZD7oBbmQIfMhHpw

###
Get http://localhost:3000/movies/2e14cff1-8a05-4cab-9c2a-4a8da3779ea3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMjIyNzBjNi1jNTg5LTQ3NWEtYTE1NS1jMTc3YTU3MzNiYjQiLCJlbWFpbCI6ImJpZWxAZW1haWwuY29tIiwiaWF0IjoxNzE1NDYwMjM1LCJleHAiOjE3MTU1NDY2MzV9.GhCVHctCuQ-db50rD-23-UsJjEpKZD7oBbmQIfMhHpw

###
Post http://localhost:3000/movies
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMjIyNzBjNi1jNTg5LTQ3NWEtYTE1NS1jMTc3YTU3MzNiYjQiLCJlbWFpbCI6ImJpZWxAZW1haWwuY29tIiwiaWF0IjoxNzE1NDYwMjM1LCJleHAiOjE3MTU1NDY2MzV9.GhCVHctCuQ-db50rD-23-UsJjEpKZD7oBbmQIfMhHpw

{
    "name": "Anabelle 2",
    "description": "Filme de terror com uma boneca versão 2",
    "category": "Terror"
}

###
Patch http://localhost:3003/movies/af187404-4aca-43e4-893f-4cac513b0e86
Content-Type: application/json

{
    "name": "Vovoz1212121ona",
    "category": "Comed212121ia"
}


###
Delete http://localhost:3000/movies/587507d7-c59c-43c1-a8c6-fcc76e3d47c3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMjIyNzBjNi1jNTg5LTQ3NWEtYTE1NS1jMTc3YTU3MzNiYjQiLCJlbWFpbCI6ImJpZWxAZW1haWwuY29tIiwiaWF0IjoxNzE1NDYwMjM1LCJleHAiOjE3MTU1NDY2MzV9.GhCVHctCuQ-db50rD-23-UsJjEpKZD7oBbmQIfMhHpw







###
Get http://localhost:3000/users/gasbr1siel@email.com

###
Post http://localhost:3000/users
Content-Type: application/json

{
    "email": "biel@email.com",
    "name": "Gabriel",
    "password": "Gabriel1"
}

