version: '3.5'

services:
  app:
    build:
      context: .
    ports:
      - 3000:3000
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_SSLMODE=${DB_SSLMODE}
      - DB_SYNCHRONIZE=${DB_SYNCHRONIZE}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRE_IN_SECONDS=${JWT_EXPIRE_IN_SECONDS}
