version: '3'
services:
  redis:
    image: redis:alpine
    container_name: mks-redis
    ports:
      - 6379:6379
  postgres:
    image: postgres:alpine
    container_name: mks-postgress
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./:/app

networks:
  default:
    name: mks-backend-net
