version: '3'
services:
  node:
    image: node
    container_name: mks-node
    build: ./
    tty: true
    stdin_open: true
    command: bash
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - postgres
    ports:
      - 3333:3333
    env_file: .env
    environment:
      - POSTGRESS_PORT=5462
      - JWT_SECRET=secret
      - JWT_EXPIRE_IN_SECONDS=86400
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_HOST=127.0.0.1
    networks:
      - default

  redis:
    image: redis:alpine
    container_name: mks-redis
    ports:
      - 6379:6379
    networks:
      - default

  postgres:
    image: postgres:alpine
    container_name: mks-postgress
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./:/app

networks:
  default:
    name: mks-backend-net
